// This file is auto-generated by @hey-api/openapi-ts

export { getApiRecursosDisponibilidadNotebooks, getApiRecursosDisponibilidadSalas, type Options, postApiReservas } from './sdk.gen';
export type { ClientOptions, GetApiRecursosDisponibilidadNotebooksData, GetApiRecursosDisponibilidadNotebooksErrors, GetApiRecursosDisponibilidadNotebooksResponse, GetApiRecursosDisponibilidadNotebooksResponses, GetApiRecursosDisponibilidadSalasData, GetApiRecursosDisponibilidadSalasErrors, GetApiRecursosDisponibilidadSalasResponse, GetApiRecursosDisponibilidadSalasResponses, PostApiReservasData, PostApiReservasErrors, PostApiReservasResponse, PostApiReservasResponses } from './types.gen';
