// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiRecursosDisponibilidadNotebooksData, GetApiRecursosDisponibilidadNotebooksErrors, GetApiRecursosDisponibilidadNotebooksResponses, GetApiRecursosDisponibilidadSalasData, GetApiRecursosDisponibilidadSalasErrors, GetApiRecursosDisponibilidadSalasResponses, PostApiReservasData, PostApiReservasErrors, PostApiReservasResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Consultar disponibilidad de salas
 */
export const getApiRecursosDisponibilidadSalas = <ThrowOnError extends boolean = false>(options: Options<GetApiRecursosDisponibilidadSalasData, ThrowOnError>): RequestResult<GetApiRecursosDisponibilidadSalasResponses, GetApiRecursosDisponibilidadSalasErrors, ThrowOnError> => (options.client ?? client).get<GetApiRecursosDisponibilidadSalasResponses, GetApiRecursosDisponibilidadSalasErrors, ThrowOnError>({ url: '/api/recursos/disponibilidad/salas', ...options });

/**
 * Consultar disponibilidad de notebooks
 */
export const getApiRecursosDisponibilidadNotebooks = <ThrowOnError extends boolean = false>(options: Options<GetApiRecursosDisponibilidadNotebooksData, ThrowOnError>): RequestResult<GetApiRecursosDisponibilidadNotebooksResponses, GetApiRecursosDisponibilidadNotebooksErrors, ThrowOnError> => (options.client ?? client).get<GetApiRecursosDisponibilidadNotebooksResponses, GetApiRecursosDisponibilidadNotebooksErrors, ThrowOnError>({ url: '/api/recursos/disponibilidad/notebooks', ...options });

/**
 * Reservar un espacio y sus recursos
 */
export const postApiReservas = <ThrowOnError extends boolean = false>(options?: Options<PostApiReservasData, ThrowOnError>): RequestResult<PostApiReservasResponses, PostApiReservasErrors, ThrowOnError> => (options?.client ?? client).post<PostApiReservasResponses, PostApiReservasErrors, ThrowOnError>({
  url: '/api/reservas',
  ...options,
  headers: {
    'Content-Type': 'application/json',
    ...options?.headers
  }
});
