// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:3000' | (string & {});
};

export type GetApiRecursosDisponibilidadSalasData = {
  body?: never;
  path?: never;
  query: {
    fechaHoraInicio: string;
    fechaHoraFin: string;
  };
  url: '/api/recursos/disponibilidad/salas';
};

export type GetApiRecursosDisponibilidadSalasErrors = {
  /**
   * Parámetros inválidos
   */
  400: unknown;
};

export type GetApiRecursosDisponibilidadSalasResponses = {
  /**
   * OK
   */
  200: {
    data: Array<{
      id: number;
      nombre: string;
      capacidad: number;
      ocupacion: number;
      cuposLibres: number;
      disponible: boolean;
      motivoNoDisponible: 'fuera_de_horario' | 'bloqueado' | 'sin_cupos' | null;
      horariosReservados: Array<{
        horaInicio: string;
        horaFin: string;
      }>;
      ubicacion: string;
    }>;
  };
};

export type GetApiRecursosDisponibilidadSalasResponse = GetApiRecursosDisponibilidadSalasResponses[keyof GetApiRecursosDisponibilidadSalasResponses];

export type GetApiRecursosDisponibilidadNotebooksData = {
  body?: never;
  path?: never;
  query: {
    fechaHoraInicio: string;
    fechaHoraFin: string;
  };
  url: '/api/recursos/disponibilidad/notebooks';
};

export type GetApiRecursosDisponibilidadNotebooksErrors = {
  /**
   * Parámetros inválidos
   */
  400: unknown;
};

export type GetApiRecursosDisponibilidadNotebooksResponses = {
  /**
   * OK
   */
  200: {
    data: Array<{
      id: number;
      nombre: string;
      capacidad: number;
      ocupacion: number;
      cuposLibres: number;
      disponible: boolean;
      motivoNoDisponible: 'fuera_de_horario' | 'bloqueado' | 'sin_cupos' | null;
      horariosReservados: Array<{
        horaInicio: string;
        horaFin: string;
      }>;
      numeroSerie: string;
      marca: string;
      modelo: string;
    }>;
  };
};

export type GetApiRecursosDisponibilidadNotebooksResponse = GetApiRecursosDisponibilidadNotebooksResponses[keyof GetApiRecursosDisponibilidadNotebooksResponses];

export type PostApiReservasData = {
  body?: {
    usuarioId: number;
    recursoIds: Array<number>;
    fechaHoraInicio: string;
    fechaHoraFin: string;
    fechaLimiteCheckIn?: string;
    observacion?: string;
  };
  path?: never;
  query?: never;
  url: '/api/reservas';
};

export type PostApiReservasErrors = {
  /**
   * Solicitud inválida o recursos no disponibles
   */
  400: unknown;
};

export type PostApiReservasResponses = {
  /**
   * Reserva creada
   */
  201: {
    data: {
      id: number;
      usuarioId: number;
      fechaHoraInicio: string;
      fechaHoraFin: string;
      fechaLimiteCheckIn: string;
      observacion: string | null;
      recursos: Array<{
        recursoId: number;
        recurso: {
          id: number;
          nombre: string;
        };
      }>;
    };
  };
};

export type PostApiReservasResponse = PostApiReservasResponses[keyof PostApiReservasResponses];
